import mongoose from "mongoose";

const Schema = mongoose.Schema;

const roomSchema = new Schema({
  room_id: {
    type: String,
    required: true,
  },
  user1: {
    username: {
      type: String,
      required: true,
    },
    color: {
      type: String,
      required: true,
    },
  },
  user2: {
    username: {
      type: String,
    },
    color: {
      type: String,
    },
  },
  figures: {
    type: Array,
    default: [
      {
        type: "Pawn",
        color: "white",
        row: 1,
        column: 2,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "white",
        row: 2,
        column: 2,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "white",
        row: 3,
        column: 2,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "white",
        row: 4,
        column: 2,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "white",
        row: 5,
        column: 2,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "white",
        row: 6,
        column: 2,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "white",
        row: 7,
        column: 2,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "white",
        row: 8,
        column: 2,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "black",
        row: 1,
        column: 7,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "black",
        row: 2,
        column: 7,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "black",
        row: 3,
        column: 7,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "black",
        row: 4,
        column: 7,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "black",
        row: 5,
        column: 7,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "black",
        row: 6,
        column: 7,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "black",
        row: 7,
        column: 7,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Pawn",
        color: "black",
        row: 8,
        column: 7,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Rook",
        color: "white",
        row: 1,
        column: 1,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Rook",
        color: "white",
        row: 8,
        column: 1,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Rook",
        color: "black",
        row: 1,
        column: 8,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Rook",
        color: "black",
        row: 8,
        column: 8,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Knight",
        color: "white",
        row: 2,
        column: 1,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Knight",
        color: "white",
        row: 7,
        column: 1,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Knight",
        color: "black",
        row: 2,
        column: 8,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Knight",
        color: "black",
        row: 7,
        column: 8,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Bishop",
        color: "white",
        row: 3,
        column: 1,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Bishop",
        color: "white",
        row: 6,
        column: 1,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Bishop",
        color: "black",
        row: 3,
        column: 8,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Bishop",
        color: "black",
        row: 6,
        column: 8,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Queen",
        color: "white",
        row: 4,
        column: 1,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "Queen",
        color: "black",
        row: 4,
        column: 8,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "King",
        color: "white",
        row: 5,
        column: 1,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
      {
        type: "King",
        color: "black",
        row: 5,
        column: 8,
        isSelected: false,
        isDead: false,
        isMoved: false,
      },
    ],
  },
});

export default mongoose.model("Room", roomSchema);
